version: "2"
services:
  microusuarios:
    build: ./microusuarios
    links:
      - db
    ports:
      - "3001:3001"
    depends_on:
      - db
  micromedic:
    build: ./micromedic
    links:
      - db
    ports:
      - "3002:3002"
    depends_on:
      - db
  microcompras:
    build: ./microcompras
    links:
      - db
      - microusuarios
      - micromedic
    ports:
      - "3003:3003"
    depends_on:
      - db
      - microusuarios
      - micromedic
  microweb:
    build: ./microweb
    links:
      - microusuarios
      - micromedic
      - microcompras
    ports:
      - "4090:80"
    depends_on:
      - microusuarios
      - micromedic
      - microcompras
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
